import React from 'react'
import Script from 'next/script'
import { TranslationProvider } from "@/context/TranslationsContext";
import { CartProvider } from '@/context/CartContext';

import './globals.css'

const baseClass = 'multi-tenant'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
}

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={baseClass} lang="en">
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
          strategy="beforeInteractive"
        />
      </head>
      <body><TranslationProvider><CartProvider>{children}</CartProvider></TranslationProvider></body>
    </html >
  )
}
