[phases.setup]
cmd = """
corepack enable &&
corepack prepare pnpm@latest --activate &&
if ! command -v docker &> /dev/null; then
  echo 'Docker not found, installing...';
  curl -fsSL https://get.docker.com | sh;
fi
"""

[phases.install]
cmd = "pnpm install --no-frozen-lockfile"

[phases.build]
cmd = """
if pnpm payload migrate:status | grep -q 'No schema changes detected'; then
  echo 'No schema changes detected, skipping migrate:create';
else
  pnpm payload migrate:create --force;
fi
pnpm payload migrate up && pnpm build
"""

[phases.prestart]
cmd = """
if [ -f docker-compose.yml ]; then
  echo 'Starting ZNet controller with Docker Compose...';
  docker compose up -d;
else
  echo 'docker-compose.yml not found, skipping.';
fi
"""

[start]
cmd = "pnpm start"
