[phases.setup]
cmd = "corepack enable && corepack prepare pnpm@latest --activate"

[phases.install]
cmd = "pnpm install --no-frozen-lockfile"

[phases.build]
cmd = """
if pnpm payload migrate:status | grep -q 'No schema changes detected'; then
  echo 'No schema changes detected, skipping migrate:create';
else
  pnpm payload migrate:create --force;
fi
pnpm payload migrate up && pnpm build
"""

[start]
cmd = "pnpm start"

[environment]
CUPS_SERVER = "/var/run/cups/cups.sock"

[environment.system_packages]
packages = ["cups", "cups-client"]

[volumes]
"/var/run/cups" = "/var/run/cups"
"/etc/cups" = "/etc/cups"
