[phases.setup]
cmd = "corepack enable && corepack prepare pnpm@latest --activate"

[phases.install]
cmd = "pnpm install --frozen-lockfile"

[phases.build]
cmd = "pnpm payload migrate up && pnpm build"

[start]
cmd = "pnpm start"
