/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    tenants: Tenant;
    users: User;
    shops: Shop;
    'payment-methods': PaymentMethod;
    'fulfillment-methods': FulfillmentMethod;
    timeslots: Timeslot;
    tables: Table;
    printers: Printer;
    pages: Page;
    customers: Customer;
    'customer-credits': CustomerCredit;
    'customer-loyalty': CustomerLoyalty;
    coupons: Coupon;
    categories: Category;
    products: Product;
    subproducts: Subproduct;
    productpopups: Productpopup;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    shops: ShopsSelect<false> | ShopsSelect<true>;
    'payment-methods': PaymentMethodsSelect<false> | PaymentMethodsSelect<true>;
    'fulfillment-methods': FulfillmentMethodsSelect<false> | FulfillmentMethodsSelect<true>;
    timeslots: TimeslotsSelect<false> | TimeslotsSelect<true>;
    tables: TablesSelect<false> | TablesSelect<true>;
    printers: PrintersSelect<false> | PrintersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-credits': CustomerCreditsSelect<false> | CustomerCreditsSelect<true>;
    'customer-loyalty': CustomerLoyaltySelect<false> | CustomerLoyaltySelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    subproducts: SubproductsSelect<false> | SubproductsSelect<true>;
    productpopups: ProductpopupsSelect<false> | ProductpopupsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  domains?:
    | {
        domain: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required.
   */
  public?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles?: ('super-admin' | 'user')[] | null;
  tenants?:
    | {
        tenant: string | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Assign shops to the user
   */
  shops?: (string | Shop)[] | null;
  username?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops".
 */
export interface Shop {
  id: string;
  tenant: string | Tenant;
  name: string;
  address?: string | null;
  phone?: string | null;
  /**
   * Details about the company associated with the shop.
   */
  company_details: {
    /**
     * The name of the company.
     */
    company_name: string;
    /**
     * The street of the company address.
     */
    street?: string | null;
    /**
     * The house number of the company address.
     */
    house_number?: string | null;
    /**
     * The city of the company address.
     */
    city?: string | null;
    /**
     * The postal code of the company address.
     */
    postal?: string | null;
    /**
     * The VAT number of the company.
     */
    vat_nr?: string | null;
    /**
     * The URL of the company website.
     */
    website_url?: string | null;
  };
  /**
   * List of dates when the shop is exceptionally closed.
   */
  exceptionally_closed_days?:
    | {
        /**
         * The date when the shop is closed.
         */
        date: string;
        /**
         * The reason for the closure.
         */
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods".
 */
export interface PaymentMethod {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * Select a payment provider.
   */
  provider: 'multisafepay' | 'cash_on_delivery';
  /**
   * Settings for MultiSafePay.
   */
  multisafepay_settings?: {
    /**
     * Enable test mode for MultiSafePay.
     */
    enable_test_mode?: boolean | null;
    /**
     * Live API Key for MultiSafePay.
     */
    live_api_key?: string | null;
    /**
     * Test API Key for MultiSafePay.
     */
    test_api_key?: string | null;
    /**
     * Select the payment methods to enable for MultiSafePay.
     */
    methods?: ('MSP_Bancontact' | 'MSP_Visa' | 'MSP_Mastercard' | 'MSP_iDeal')[] | null;
  };
  /**
   * Enable or disable this payment method.
   */
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fulfillment-methods".
 */
export interface FulfillmentMethod {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * Select the type of fulfillment method.
   */
  method_type: 'delivery' | 'takeaway' | 'dine_in';
  /**
   * Specify the base delivery fee, if applicable.
   */
  delivery_fee?: number | null;
  /**
   * Specify the minimum order amount for this fulfillment method.
   */
  minimum_order?: number | null;
  /**
   * Specify the extra cost per kilometer for delivery.
   */
  extra_cost_per_km?: number | null;
  /**
   * Enable or disable this fulfillment method.
   */
  enabled?: boolean | null;
  /**
   * Additional settings specific to this fulfillment method.
   */
  settings?: {
    /**
     * Specify the delivery radius in kilometers.
     */
    delivery_radius?: number | null;
    /**
     * Add specific instructions for takeaway orders.
     */
    pickup_instructions?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeslots".
 */
export interface Timeslot {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * The fulfillment method associated with this timeslot.
   */
  method_id: string | FulfillmentMethod;
  /**
   * Specify time ranges for selected days.
   */
  days?:
    | {
        /**
         * Select the day for these time ranges.
         */
        day: '1' | '2' | '3' | '4' | '5' | '6' | '7';
        /**
         * Define multiple time ranges for this day.
         */
        time_ranges?:
          | {
              /**
               * Start time for this range (e.g., 13:00).
               */
              start_time: string;
              /**
               * End time for this range (e.g., 14:00).
               */
              end_time: string;
              /**
               * Interval in minutes for this range.
               */
              interval_minutes: number;
              /**
               * Maximum orders per interval. Leave empty for unlimited.
               */
              max_orders?: number | null;
              /**
               * Enable or disable this range.
               */
              status?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables".
 */
export interface Table {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * Unique table number within a shop.
   */
  table_num: number;
  /**
   * Current status of the table.
   */
  status?: ('0' | '1' | '2') | null;
  /**
   * Number of persons that can fit on this table.
   */
  capacity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printers".
 */
export interface Printer {
  id: string;
  tenant: string | Tenant;
  /**
   * Select the shop associated with this printer.
   */
  printername: string | Shop;
  /**
   * Settings for this shop printer.
   */
  printer_settings?: {
    /**
     * Default printer ID.
     */
    default_printer_id?: string | null;
    /**
     * Enable printing functionality.
     */
    print_enabled?: boolean | null;
    /**
     * Enable kitchen printing functionality.
     */
    kitchen_enabled?: boolean | null;
    /**
     * Enable customer printing functionality.
     */
    customer_enabled?: boolean | null;
    /**
     * Number of kitchen tickets to print.
     */
    kitchen_ticket_amount?: number | null;
    /**
     * Printer ID for the kitchen printer.
     */
    kitchen_printer_id?: string | null;
    /**
     * List of Kiosk printers (add multiple).
     */
    kiosk_printers?:
      | {
          /**
           * Kiosk ID.
           */
          kiosk_id?: string | null;
          /**
           * Kiosk PrintNode ID.
           */
          kiosk_printnode_id?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Enable printing of category headers.
     */
    print_category_headers?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  slug?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * First name of the customer.
   */
  firstname: string;
  /**
   * Last name of the customer.
   */
  lastname: string;
  /**
   * Company name associated with the customer (if applicable).
   */
  company_name?: string | null;
  /**
   * Street address of the customer.
   */
  street?: string | null;
  /**
   * House number of the customer.
   */
  house_number?: string | null;
  /**
   * City of the customer.
   */
  city?: string | null;
  /**
   * Postal code of the customer.
   */
  postal_code?: string | null;
  /**
   * VAT number for business customers.
   */
  vat_number?: string | null;
  /**
   * Email address of the customer.
   */
  email: string;
  /**
   * Phone number of the customer.
   */
  phone?: string | null;
  tags?:
    | {
        /**
         * Tag ID associated with the customer.
         */
        tag_id?: string | null;
        /**
         * Type of tag (e.g., loyalty, preference).
         */
        tag_type?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Timestamp for last modification.
   */
  modtime: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-credits".
 */
export interface CustomerCredit {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * The customer this credit is assigned to.
   */
  customerid: string | Customer;
  /**
   * Credit value available for the customer.
   */
  value: number;
  /**
   * Optional tag identifier for this credit.
   */
  tagid?: string | null;
  /**
   * Optional tag type for this credit.
   */
  tagtype?: string | null;
  /**
   * Product associated with this credit (if applicable).
   */
  productid?: (string | null) | Product;
  /**
   * Category associated with this credit (if applicable).
   */
  categoryid?: (string | null) | Category;
  /**
   * Payment method associated with this credit.
   */
  paymenttype?: (string | null) | PaymentMethod;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  categories: (string | Category)[];
  name: string;
  /**
   * Use a unified sale price for all fulfillment methods.
   */
  price_unified?: boolean | null;
  /**
   * Unified sale price
   */
  price?: number | null;
  /**
   * Sale price for dine-in
   */
  price_dinein?: number | null;
  /**
   * Sale price for takeaway
   */
  price_takeaway?: number | null;
  /**
   * Sale price for delivery
   */
  price_delivery?: number | null;
  /**
   * Enable stock tracking for this product
   */
  enable_stock?: boolean | null;
  /**
   * Stock quantity
   */
  quantity?: number | null;
  /**
   * Specify the VAT percentage (e.g., 6, 12, 21)
   */
  tax: number;
  /**
   * Numeric identifier for the applicable tax table
   */
  tax_dinein?: number | null;
  /**
   * Enable product visibility in the POS system
   */
  posshow?: boolean | null;
  /**
   * Product barcode (if applicable)
   */
  barcode?: string | null;
  /**
   * URL for the product image
   */
  image_url?: string | null;
  /**
   * Timestamp for last modification
   */
  modtime: number;
  /**
   * Webshop description for the product
   */
  webdescription?: string | null;
  /**
   * Show this product in the webshop
   */
  webshopshow?: boolean | null;
  /**
   * Allow this product to be ordered via the webshop
   */
  webshoporderable?: boolean | null;
  /**
   * Product status (enabled or disabled)
   */
  status: 'enabled' | 'disabled';
  /**
   * Assign popups to this product and define their order.
   */
  productpopups?:
    | {
        /**
         * Select a popup to assign to this product.
         */
        popup: string | Productpopup;
        /**
         * Order in which this popup appears in the product workflow.
         */
        order: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  name: string;
  /**
   * URL for the category image
   */
  image_url?: string | null;
  /**
   * Timestamp for last modification
   */
  modtime: number;
  /**
   * Category status (enabled or disabled)
   */
  status: 'enabled' | 'disabled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productpopups".
 */
export interface Productpopup {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * Title of the popup, e.g., "Choose Your Sauce"
   */
  popup_title: string;
  /**
   * Optional: Associate this popup with a specific product.
   */
  product?: (string | null) | Product;
  /**
   * Allow selecting multiple options in this popup.
   */
  multiselect?: boolean | null;
  /**
   * Require selection of an option in the cash register.
   */
  required_option_cashregister?: boolean | null;
  /**
   * Require selection of an option in the webshop.
   */
  required_option_webshop?: boolean | null;
  /**
   * Minimum number of options to select.
   */
  minimum_option?: number | null;
  /**
   * Maximum number of options to select. Set to 0 for no limit.
   */
  maximum_option?: number | null;
  /**
   * Default subproduct selected when the popup loads.
   */
  default_checked_subproduct?: (string | null) | Subproduct;
  /**
   * List of subproducts associated with this popup.
   */
  subproducts?: (string | Subproduct)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subproducts".
 */
export interface Subproduct {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  name: string;
  /**
   * Use a unified sale price for all fulfillment methods.
   */
  price_unified?: boolean | null;
  /**
   * Unified sale price
   */
  price?: number | null;
  /**
   * Sale price for dine-in
   */
  price_dinein?: number | null;
  /**
   * Sale price for takeaway
   */
  price_takeaway?: number | null;
  /**
   * Sale price for delivery
   */
  price_delivery?: number | null;
  /**
   * Enable linking to an existing product. If enabled, price and tax fields will be hidden.
   */
  linked_product_enabled?: boolean | null;
  linked_product?: (string | null) | Product;
  /**
   * Enable stock tracking for this subproduct
   */
  stock_enabled?: boolean | null;
  /**
   * Stock quantity
   */
  stock_quantity?: number | null;
  /**
   * Specify the VAT percentage (e.g., 6, 12, 21)
   */
  tax?: number | null;
  /**
   * Specify the VAT percentage for dinein (e.g., 6, 12, 21)
   */
  tax_table?: number | null;
  /**
   * URL for the subproduct image
   */
  image_url?: string | null;
  /**
   * Timestamp for last modification
   */
  modtime: number;
  /**
   * Mark this subproduct as deleted
   */
  deleted?: boolean | null;
  /**
   * Subproduct status (enabled or disabled)
   */
  status: 'enabled' | 'disabled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-loyalty".
 */
export interface CustomerLoyalty {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * Name of the loyalty program, e.g., "VIP Rewards".
   */
  program_name: string;
  /**
   * Number of points awarded per purchase.
   */
  points_per_purchase: number;
  /**
   * Conversion ratio for points to currency, e.g., 100 points = $1.
   */
  redeem_ratio: number;
  /**
   * Status of the loyalty program.
   */
  status: 'active' | 'inactive';
  /**
   * Additional details about the loyalty program.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  tenant: string | Tenant;
  shops: (string | Shop)[];
  /**
   * Unique barcode for the coupon.
   */
  barcode: string;
  /**
   * Value of the coupon (percentage or fixed amount).
   */
  value: number;
  /**
   * Type of value for the coupon.
   */
  value_type: 'percentage' | 'fixed';
  /**
   * Start date for the coupon validity.
   */
  valid_from: string;
  /**
   * End date for the coupon validity.
   */
  valid_until: string;
  /**
   * Maximum number of times the coupon can be used. Leave empty for unlimited.
   */
  max_uses?: number | null;
  /**
   * Number of times this coupon has been used.
   */
  uses?: number | null;
  /**
   * Mark if the coupon has already been fully used.
   */
  used?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'shops';
        value: string | Shop;
      } | null)
    | ({
        relationTo: 'payment-methods';
        value: string | PaymentMethod;
      } | null)
    | ({
        relationTo: 'fulfillment-methods';
        value: string | FulfillmentMethod;
      } | null)
    | ({
        relationTo: 'timeslots';
        value: string | Timeslot;
      } | null)
    | ({
        relationTo: 'tables';
        value: string | Table;
      } | null)
    | ({
        relationTo: 'printers';
        value: string | Printer;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'customer-credits';
        value: string | CustomerCredit;
      } | null)
    | ({
        relationTo: 'customer-loyalty';
        value: string | CustomerLoyalty;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'subproducts';
        value: string | Subproduct;
      } | null)
    | ({
        relationTo: 'productpopups';
        value: string | Productpopup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  slug?: T;
  public?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  shops?: T;
  username?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shops_select".
 */
export interface ShopsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  address?: T;
  phone?: T;
  company_details?:
    | T
    | {
        company_name?: T;
        street?: T;
        house_number?: T;
        city?: T;
        postal?: T;
        vat_nr?: T;
        website_url?: T;
      };
  exceptionally_closed_days?:
    | T
    | {
        date?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods_select".
 */
export interface PaymentMethodsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  provider?: T;
  multisafepay_settings?:
    | T
    | {
        enable_test_mode?: T;
        live_api_key?: T;
        test_api_key?: T;
        methods?: T;
      };
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fulfillment-methods_select".
 */
export interface FulfillmentMethodsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  method_type?: T;
  delivery_fee?: T;
  minimum_order?: T;
  extra_cost_per_km?: T;
  enabled?: T;
  settings?:
    | T
    | {
        delivery_radius?: T;
        pickup_instructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeslots_select".
 */
export interface TimeslotsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  method_id?: T;
  days?:
    | T
    | {
        day?: T;
        time_ranges?:
          | T
          | {
              start_time?: T;
              end_time?: T;
              interval_minutes?: T;
              max_orders?: T;
              status?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables_select".
 */
export interface TablesSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  table_num?: T;
  status?: T;
  capacity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "printers_select".
 */
export interface PrintersSelect<T extends boolean = true> {
  tenant?: T;
  printername?: T;
  printer_settings?:
    | T
    | {
        default_printer_id?: T;
        print_enabled?: T;
        kitchen_enabled?: T;
        customer_enabled?: T;
        kitchen_ticket_amount?: T;
        kitchen_printer_id?: T;
        kiosk_printers?:
          | T
          | {
              kiosk_id?: T;
              kiosk_printnode_id?: T;
              id?: T;
            };
        print_category_headers?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  firstname?: T;
  lastname?: T;
  company_name?: T;
  street?: T;
  house_number?: T;
  city?: T;
  postal_code?: T;
  vat_number?: T;
  email?: T;
  phone?: T;
  tags?:
    | T
    | {
        tag_id?: T;
        tag_type?: T;
        id?: T;
      };
  modtime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-credits_select".
 */
export interface CustomerCreditsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  customerid?: T;
  value?: T;
  tagid?: T;
  tagtype?: T;
  productid?: T;
  categoryid?: T;
  paymenttype?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-loyalty_select".
 */
export interface CustomerLoyaltySelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  program_name?: T;
  points_per_purchase?: T;
  redeem_ratio?: T;
  status?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  barcode?: T;
  value?: T;
  value_type?: T;
  valid_from?: T;
  valid_until?: T;
  max_uses?: T;
  uses?: T;
  used?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  name?: T;
  image_url?: T;
  modtime?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  categories?: T;
  name?: T;
  price_unified?: T;
  price?: T;
  price_dinein?: T;
  price_takeaway?: T;
  price_delivery?: T;
  enable_stock?: T;
  quantity?: T;
  tax?: T;
  tax_dinein?: T;
  posshow?: T;
  barcode?: T;
  image_url?: T;
  modtime?: T;
  webdescription?: T;
  webshopshow?: T;
  webshoporderable?: T;
  status?: T;
  productpopups?:
    | T
    | {
        popup?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subproducts_select".
 */
export interface SubproductsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  name?: T;
  price_unified?: T;
  price?: T;
  price_dinein?: T;
  price_takeaway?: T;
  price_delivery?: T;
  linked_product_enabled?: T;
  linked_product?: T;
  stock_enabled?: T;
  stock_quantity?: T;
  tax?: T;
  tax_table?: T;
  image_url?: T;
  modtime?: T;
  deleted?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productpopups_select".
 */
export interface ProductpopupsSelect<T extends boolean = true> {
  tenant?: T;
  shops?: T;
  popup_title?: T;
  product?: T;
  multiselect?: T;
  required_option_cashregister?: T;
  required_option_webshop?: T;
  minimum_option?: T;
  maximum_option?: T;
  default_checked_subproduct?: T;
  subproducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}